services:
  app:
    build: .
    image: rallue/reflex-servers:latest
    container_name: servers_reflex
    ports:
      - "3003:3003"
      - "8003:8003"
    volumes:
      - reflex_data:/app
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://<IP-DE-TU-SERVIDOR>:8003
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
    restart: always

volumes:
  reflex_data:
