services:
  app:
    image: rallue/reflex-servers:latest
    container_name: servers_reflex
    ports:
      - "3003:3000" # Frontend (Interno 3000)
      - "8003:8000" # Backend (Interno 8000)
    volumes:
      - reflex_data:/app
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=${API_URL:-http://localhost:8003}
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
    restart: always

volumes:
  reflex_data:
