"""Add service user and password

Revision ID: 3fc7487d7655
Revises: 022ce2134376
Create Date: 2026-03-20 20:19:56.204002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3fc7487d7655'
down_revision: Union[str, Sequence[str], None] = '022ce2134376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('user')

    # ### end Alembic commands ###
