"""Add service observations

Revision ID: 6f3919a2518a
Revises: b1e58f5e3396
Create Date: 2026-03-20 19:52:55.897785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6f3919a2518a'
down_revision: Union[str, Sequence[str], None] = 'b1e58f5e3396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observations', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('observations')

    # ### end Alembic commands ###
